=== chutney-testing/chutney-legacy/nx/libs/data-models/schema.scenario.v2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "definitions": {
    "step": {
      "type": "object",
      "required": ["description"],
      "properties": {
        "description": {
          "type": "string"
        },
        "subSteps": {
          "$ref": "#/definitions/step"
        },
        "implementation": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "target": {
              "type": "string",
              "enum": []
            },
            "inputs": {
              "type": "object"
            },
            "outputs": {
              "type": "object"
            }
          }
        },
        "strategy": {
          "type": "object"
        }
      }
    }
  },
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "givens": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/step"
      },
      "default": []
    },
    "when": {
      "$ref": "#/definitions/step"
    },
    "thens": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/step"
      },
      "default": []
    }
  },
  "required": ["title", "description", "givens", "when", "thens"]
}

=== chutney-testing/chutney-legacy/server/src/main/test.chutney.json
{
    "title": "Envoi d'une consigne IRVE non recevable - date dépassée",
    "description": "Envoi d'une consigne IRVE non recevable - date dépassée",
    "givens": [
        {
            "description": "Given un prm PMEPMI",
            "implementation": {
                "type": "context-put",
                "inputs": {
                    "entries": {
                        "idPrm": "30001610125952",
                        "adsBoitier": "0219DA01772307"
                    }
                }
            }
        },
        {
            "description": "Et les variables suivantes",
            "implementation": {
                "type": "context-put",
                "inputs": {
                    "entries": {
                        "maCorrelationId": "${#generate().uuid()}",
                        "idDemande": "PXR_ICOEUR_30002210740627_1591881109755",
                        "dateLimiteExecution": "2000-12-31T12:00:00+01:00",
                        "dateDebut": "2021-03-29T12:00:00.000+01:00"
                    }
                }
            }
        },
        {
            "description": "And la déclaration des queues",
            "implementation": {
                "type": "context-put",
                "inputs": {
                    "entries": {
                        "icoeurQueueCrPixr": "icoeur.queue.cr.pixr"
                    }
                }
            }
        }
    ],
    "when": {
        "description": "And la déclaration des queues",
        "implementation": {
            "type": "context-put",
            "inputs": {
                "entries": {
                    "icoeurQueueCrPixr": "icoeur.queue.cr.pixr"
                }
            }
        }
    },
    "thens": [
        {
            "description": "Validation du format de la notification de consigne IRVE non recevable",
            "implementation": {
                "type": "success",
                "inputs": {
                    "fake_param": "fake_value"
                }
            }
        }
    ]
}
